KRS_G54/KRS_G54/Models/Subject.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Xunit.Sdk;

namespace KRS_G54.Models
{
    public partial class Subject
    {
        public Subject()
        {
            Classes = new HashSet<Class>();
            ExamKnowledges = new HashSet<ExamKnowledge>();
            Exams = new HashSet<Exam>();
            Flashcards = new HashSet<Flashcard>();
            Knowledges = new HashSet<Knowledge>();
            Lessons = new HashSet<Lesson>();
        }

        public int SubjectId { get; set; }
        [StringLength(100, MinimumLength = 10, ErrorMessage = "Subject name must be at least 10 characters long")]
        public string SubjectName { get; set; } = null!;
        public int? AccountId { get; set; }
        [Required(ErrorMessage = "Subject code is required")]
        [StringLength(6, ErrorMessage = "Subject code must have exactly 6 characters")]
        [RegularExpression(@"^[A-Z]{3}\d{3}$", ErrorMessage = "Subject code must be in the format of 3 uppercase letters followed by 3 digits. Ex:VNR202")]

        public string SubjectCode { get; set; } = null!;
        public bool? Status { get; set; }
        public string? Description { get; set; }

        public virtual Account? Account { get; set; }
        public virtual ICollection<Class> Classes { get; set; }
        public virtual ICollection<ExamKnowledge> ExamKnowledges { get; set; }
        public virtual ICollection<Exam> Exams { get; set; }
        public virtual ICollection<Flashcard> Flashcards { get; set; }
        public virtual ICollection<Knowledge> Knowledges { get; set; }
        public virtual ICollection<Lesson> Lessons { get; set; }
    }
}

KRS_G54/KRS_G54/Areas/Admin/Controllers/SubjectController.cs
using KRS_G54.Filters;
using KRS_G54.Models;
using KRS_G54.Repository.IRepsitory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;
using System.Data;
using System.Security.Claims;
using System.Security.Principal;
using X.PagedList;

namespace KRS_G54.Areas.Admin.Controllers
{
    [ServiceFilter(typeof(AdminRoleAttribute))]
    [Area("Admin")]
    public class SubjectController : Controller
    {
        private readonly ISubjectRepository _subjectrepo;
        private readonly abcContext _context;

        public SubjectController(ISubjectRepository subjectrepo, abcContext context)
        {
            _subjectrepo = subjectrepo;
            _context = context;
        }

        public IActionResult Index(int? page)
        {
            var subjects = _context.Subjects.Include(s => s.Account).ToList();
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(subjects.ToPagedList(pageNumber, pageSize));
        }
        public IActionResult Search(string searchString, int? page)
        {

            var subjects = _context.Subjects.Include(u => u.Account).ToList();
            ViewBag.SearchString = searchString ?? String.Empty;
            if (!string.IsNullOrEmpty(searchString))
            {
                subjects = subjects.Where(u => u.SubjectName.IndexOf(searchString, StringComparison.OrdinalIgnoreCase) >= 0 || u.SubjectCode.IndexOf(searchString, StringComparison.OrdinalIgnoreCase) >= 0).ToList();
            }
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View("Index", subjects.ToPagedList(pageNumber, pageSize));
        }
        [HttpPost]
        public IActionResult UpdateStatus(int id)
        {
            var subject = _context.Subjects.Find(id);
            if (subject != null)
            {
                subject.Status = !subject.Status;
                _context.SaveChanges();
            }
            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public ActionResult Create()
        {
            var account = _context.Accounts.Where(a => a.RoleId == 2).ToList();
            var AccountSelectList = new SelectList(account, "AccountId", "UserName");
            ViewBag.AccountSelectList = AccountSelectList;
            return View();
        }
        [HttpPost]
        public ActionResult Create(Subject subject)
        {
            ModelState.Remove("Account");
            if (ModelState.IsValid)
            {
                if (_subjectrepo.GetAll().Any(p => p.SubjectCode == subject.SubjectCode))
                {
                    ModelState.AddModelError("SubjectCode", "A subject code with the same code already exists.");
                    var account = _context.Accounts.Where(a => a.RoleId == 2).ToList();
                    var AccountSelectList = new SelectList(account, "AccountId", "UserName");
                    ViewBag.AccountSelectList = AccountSelectList;
                    return View(subject);
                }
                try
                {
                    _subjectrepo.Add(subject);
                    _subjectrepo.Save();
                    return RedirectToAction(nameof(Index));
                }
                catch
                {
                    var account = _context.Accounts.Where(a => a.RoleId == 2).ToList();
                    var AccountSelectList = new SelectList(account, "AccountId", "UserName");
                    ViewBag.AccountSelectList = AccountSelectList;
                    return View(subject);
                }
            }
            else
            {
                var account = _context.Accounts.Where(a => a.RoleId == 2).ToList();
                var AccountSelectList = new SelectList(account, "AccountId", "UserName");
                ViewBag.AccountSelectList = AccountSelectList;
                return View(subject);
            }
        }
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id.HasValue)
            {
                var subject = _subjectrepo.Find(id.Value);
                if (subject != null)
                {
                    var account = _context.Accounts.Where(a => a.RoleId == 2).ToList();
                    var AccountSelectList = new SelectList(account, "AccountId", "UserName");
                    ViewBag.AccountSelectList = AccountSelectList;
                    return View(subject);
                }
            }
            return RedirectToAction(nameof(Index));
        }
        [HttpPost]
        public ActionResult Edit(int? id, Subject subject)
        {
            ModelState.Remove("Account");
            if (ModelState.IsValid)
            {
                if (id != subject.SubjectId)
                {
                    return NotFound();
                }
                try
                {
                    _subjectrepo.Update(subject);
                    _subjectrepo.Save();
                    return RedirectToAction(nameof(Index));
                }
                catch
                {
                    var account = _context.Accounts.Where(a => a.RoleId == 2).ToList();
                    var AccountSelectList = new SelectList(account, "AccountId", "UserName");
                    ViewBag.AccountSelectList = AccountSelectList;
                    return View(subject);
                }
            }
            else
            {
                var account = _context.Accounts.Where(a => a.RoleId == 2).ToList();
                var AccountSelectList = new SelectList(account, "AccountId", "UserName");
                ViewBag.AccountSelectList = AccountSelectList;
                return View(subject);
            }
        }
        public IActionResult SortByName(string sortOrder, int? page)
        {
            ViewData["SortOrder"] = sortOrder;

            var subjects = _context.Subjects.Include(u => u.Account).ToList();

            switch (sortOrder)
            {
                case "asc":
                    subjects = subjects.OrderBy(u => u.SubjectName).ToList();
                    break;
                case "desc":
                    subjects = subjects.OrderByDescending(u => u.SubjectName).ToList();
                    break;
                default:
                    // Mặc định sắp xếp theo thứ tự tăng dần
                    subjects = subjects.OrderBy(u => u.SubjectName).ToList();
                    break;
            }
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View("Index", subjects.ToPagedList(pageNumber, pageSize));
        }
        public IActionResult FilterByStatus(bool? status, int? page)
        {
            var subjects = _context.Subjects.Include(u => u.Account).ToList();

            if (status.HasValue)
            {
                subjects = subjects.Where(u => u.Status == status.Value).ToList();
            }
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View("Index", subjects.ToPagedList(pageNumber, pageSize));
        }


    }
}

KRS_G54/KRS_G54/Areas/Admin/Views/Subject/Create.cshtml
@model KRS_G54.Models.Subject
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, AuthoringTagHelpers
@{
    ViewData["Title"] = "Create";
    Layout = "/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<script src="~/ckeditor/ckeditor.js"></script>
<h1 style="text-align:center">Create Subject</h1>
<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row">
                <div class="form-group col-lg-6">
                    <label>SubjectName<span class="text-danger">*</span></label>
                    <input asp-for="SubjectName" class="form-control" required />
                    <span asp-validation-for="SubjectName" class="text-danger"></span>
                </div>
                <div class="form-group col-lg-6">
                    <label>SubjectCode<span class="text-danger">*</span></label>
                    <input asp-for="SubjectCode" class="form-control" required />
                    <span asp-validation-for="SubjectCode" class="text-danger"></span>
                </div>
            </div>
            <div class="row">
                  <div class="form-group col-lg-6 ">
                <label class="control-label">Subject Manager<span class="text-danger">*</span></label>
                <select asp-for="AccountId" class="form-control" asp-items="@ViewBag.AccountSelectList">
                </select>
            </div>
            <div class="form-group col-lg-6">
                <label class="control-label">Status</label>
                <br />
                <div class="custom-control custom-switch" style="margin-top:6px">
                    <input type="checkbox" class="custom-control-input" id="toggleStatus" name="Status" value="true" />
                    <label class="custom-control-label" for="toggleStatus" id="toggleLabel">Deactivate</label>
                </div>
                <input type="hidden" name="Status" value="false" />
            </div>
            </div>
          
            <div class="form-group col-lg-12" style="padding-left:0px">
                <label asp-for="Description" class="control-label"></label>
                @Html.TextAreaFor(Model => Model.Description, new {@id = "description",
                @class = "form-control"})
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>


            <div>
                @Html.ActionLink("Back to List", "Index",new {}, new {@class = "btn btn-outline-primary text-black mr-2"})
                <input type="submit" value="Create" class="btn btn-success" />
            </div>

        </form>
    </div>

KRS_G54/KRS_G54/Areas/Admin/Views/Subject/Edit.cshtml
@model KRS_G54.Models.Subject
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, AuthoringTagHelpers
@{
    ViewData["Title"] = "Edit";
    Layout = "/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<script src="~/ckeditor/ckeditor.js"></script>
<h1 style="text-align:center">Edit Subject</h1>

<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group col-lg-6" style="display:none">
                <label asp-for="SubjectId" class="control-label"></label>
                <input asp-for="SubjectId" class="form-control" readonly />
                <span asp-validation-for="SubjectId" class="text-danger"></span>
            </div>
            <div class="row">
                <div class="form-group col-lg-6">
                    <label asp-for="SubjectName" class="control-label"></label>
                    <input asp-for="SubjectName" class="form-control" required />
                    <span asp-validation-for="SubjectName" class="text-danger"></span>
                </div>
                <div class="form-group col-lg-6">
                    <label asp-for="SubjectCode" class="control-label"></label>
                    <input asp-for="SubjectCode" class="form-control" required />
                    <span asp-validation-for="SubjectCode" class="text-danger"></span>
                </div>
            </div>
            <div class="row">
                
                <div class="form-group col-lg-6">
                    <label class="control-label">Subject Manager</label>
                    <select asp-for="AccountId" class="form-control" asp-items="@ViewBag.AccountSelectList">
                    </select>

                    <span asp-validation-for="AccountId" class="text-danger"></span>
                </div>
               
            </div>
            <div class="form-group col-lg-6">
                <label class="control-label">Status</label>
                <br />
                <div class="custom-control custom-switch" style="margin-top:6px">
                    <input type="checkbox" class="custom-control-input" id="toggleStatus" name="Status" value="true" @(Model.Status.GetValueOrDefault() ? "checked" : "") /> 
                    <label class="custom-control-label" for="toggleStatus" id="toggleLabel">@(Model.Status.GetValueOrDefault() ? "Activate" : "Deactivate")</label>
                </div>
                <input type="hidden" name="Status" value="false" />
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                @Html.TextAreaFor(Model => Model.Description, new {@id = "description",
                @class = "form-control"})
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="form-group">
                @Html.ActionLink("Back to List", "Index",new {}, new {@class = "btn btn-outline-primary text-black mr-2"})
                <input type="submit" value="Update" class="btn btn-success" />
            </div>
            
          
        </form>
    </div>
</div>

KRS_G54/KRS_G54/Areas/Admin/Views/Subject/Index.cshtml
@using X.PagedList;
@model IPagedList<KRS_G54.Models.Subject>
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, AuthoringTagHelpers
@{
    ViewData["Title"] = "Manager Page";
    Layout = "/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h1>Subject Management</h1>
<div class="container" style="margin:0px">
    <div class="row" style=" display: inline-flex;justify-content: space-around;">
       

        <div class="col">
            <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Fillter by Status...
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownSortButton">
                    <a class="dropdown-item" href="@Url.Action("FilterByStatus", new { status = (bool?)null })">All</a> <!-- Tùy chọn "All" -->
                    <a class="dropdown-item" href="@Url.Action("FilterByStatus", new { status = true })">Active</a>
                    <a class="dropdown-item" href="@Url.Action("FilterByStatus", new { status = false })">Inactive</a>
                </div>
            </div>
        </div>
        <div class="col">
            <form asp-controller="Subject" asp-action="Search" method="get">
                <div class="input-group">
                    <input type="text" name="searchString" class="form-control" placeholder="Search..." value="@ViewBag.SearchString">
                    <div class="input-group-append">
                        <button type="submit" class="btn btn-primary">Search</button>
                    </div>
                </div>
            </form>
        </div>
       
    </div>



</div>

<table class="table" style="margin-top:30px">
    <thead>
        <tr>
            <th>Subject Code</th>
            <th>Subject Name <a href="@Url.Action("SortByName", new { sortOrder = "asc" })"><span class="arrow-up"></span></a>  <a href="@Url.Action("SortByName", new { sortOrder = "desc" })"><span class="arrow-down"></span></a></th>
            <th>Manager</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var subject in Model)
        {
            <tr>
                <td>@subject.SubjectCode</td>
                <td>@subject.SubjectName</td>
                <td>@subject.Account.UserName</td>
                <td>@(subject.Status.HasValue && subject.Status.Value ? "Activate" : "Deactivate")</td>
                <td>
                    <form method="post" asp-action="UpdateStatus">
                        <input type="hidden" name="Id" value="@subject.SubjectId" />
                        <div class="d-flex align-items-center">
                            @if (subject.Status.HasValue && subject.Status.Value)
                            {
                                <button type="submit" class="btn btn-warning fixed-size-button" style="margin-right:10px" onclick="return confirm('Are you sure to Inactive this ?')">
                                    Deactivate
                                </button>
                            }
                            else
                            {
                                <button type="submit" class="btn btn-success fixed-size-button" style="margin-right:10px" onclick="return confirm('Are you sure to Active this ?')">
                                    Activate
                                </button>
                            }
                            @Html.ActionLink("Edit", "Edit", new {Id = subject.SubjectId}, new {@class = "btn btn-success"})
                        </div>
                    </form>
                </td>
              
            </tr>
        }
    </tbody>
</table>
<div class="text-center">
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            <li class="page-item @(Model.HasPreviousPage ? "" : "disabled")">
                <a class="page-link" href="@Url.Action("Index", new { page = Model.PageNumber - 1 })" tabindex="-1" style="background-color: transparent;border: none;">⬅️</a>
            </li>
            @for (var i = 1; i <= Model.PageCount; i++)
            {
                <li class="page-item @(i == Model.PageNumber ? "active" : "")">
                    <a class="page-link" href="@Url.Action("Index", new { page = i })">@i</a>
                </li>
            }
            <li class="page-item @(Model.HasNextPage ? "" : "disabled")">
                <a class="page-link" href="@Url.Action("Index", new { page = Model.PageNumber + 1 })" style="background-color: transparent;border: none;">➡️</a>
            </li>
        </ul>
    </nav>
</div>