KRS_G54/KRS_G54/Models/Lesson.cs
using System;
using System.Collections.Generic;

namespace KRS_G54.Models
{
    public partial class Lesson
    {
        public Lesson()
        {
            ExamKnowledges = new HashSet<ExamKnowledge>();
            Knowledges = new HashSet<Knowledge>();
        }

        public int LessonId { get; set; }
        public string Topic { get; set; } = null!;
        public int SubjectId { get; set; }
        public double Order { get; set; }

        public virtual Subject Subject { get; set; } = null!;
        public virtual ICollection<ExamKnowledge> ExamKnowledges { get; set; }
        public virtual ICollection<Knowledge> Knowledges { get; set; }
    }
}

KRS_G54/KRS_G54/Areas/Manager/Controllers/LessonController.cs
using X.PagedList;
using KRS_G54.Models;
using KRS_G54.Repository.IRepsitory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using KRS_G54.Filters;

namespace KRS_G54.Areas.Manager.Controllers
{
    [ServiceFilter(typeof(ManagerRoleAttribute))]
    [Area("Manager")]
    public class LessonController : Controller
	{
		private readonly abcContext _context;
		private readonly ILessonRepository _repo;
		public LessonController(abcContext context, ILessonRepository repo)
		{
			_repo = repo;
			_context = context;
		}

		public IActionResult Index(int? page)
		{
            var subjects = _context.Subjects.ToList();
            ViewBag.Subjects = subjects;
            var lessons = _context.Lessons.Include(s => s.Subject).ToList();
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(lessons.ToPagedList(pageNumber, pageSize));
		}
        [HttpGet]
        public ActionResult Create()
        {
            var subjects = _context.Subjects.ToList();
            var SubjectSelectList = new SelectList(subjects, "SubjectId", "SubjectName");
            ViewBag.SubjectSelectList = SubjectSelectList;
            return View();
        }
        [HttpPost]
        public ActionResult Create(Lesson lesson)
        {
            ModelState.Remove("Subject");
            if (ModelState.IsValid)
            {
                if (_repo.GetAll().Any(p => p.Topic == lesson.Topic))
                {
                    ModelState.AddModelError("Topic", "Topic has already exists.");
                    var subjects = _context.Subjects.ToList();
                    var SubjectSelectList = new SelectList(subjects, "SubjectId", "SubjectName");
                    ViewBag.SubjectSelectList = SubjectSelectList;
                    return View(lesson);
                }else if(_repo.GetAll().Any(p => p.Order == lesson.Order))
                {
                    ModelState.AddModelError("Order", "Slot has already exists.");
                    var subjects = _context.Subjects.ToList();
                    var SubjectSelectList = new SelectList(subjects, "SubjectId", "SubjectName");
                    ViewBag.SubjectSelectList = SubjectSelectList;
                    return View(lesson);
                }
                else if (lesson.Order > 30)
                {
                    ModelState.AddModelError("Order", "Slot cannot be greater than 30.");
                    var subjects = _context.Subjects.ToList();
                    var SubjectSelectList = new SelectList(subjects, "SubjectId", "SubjectName");
                    ViewBag.SubjectSelectList = SubjectSelectList;
                    return View(lesson);
                }
                try
                {
                    _repo.Add(lesson);
                    _repo.Save();
                    return RedirectToAction(nameof(Index));
                }
                catch
                {
                    var subjects = _context.Subjects.ToList();
                    var SubjectSelectList = new SelectList(subjects, "SubjectId", "SubjectName");
                    ViewBag.SubjectSelectList = SubjectSelectList;
                    return View(lesson);
                }
            }else
            {
                var subjects = _context.Subjects.ToList();
                var SubjectSelectList = new SelectList(subjects, "SubjectId", "SubjectName");
                ViewBag.SubjectSelectList = SubjectSelectList;
                return View(lesson);
            }
            

        }
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            
            if (id.HasValue)
            {
                var lesson = _repo.Find(id.Value);
                if (lesson != null)
                {
                    var subjects = _context.Subjects.ToList();
                    var SubjectSelectList = new SelectList(subjects, "SubjectId", "SubjectName");
                    ViewBag.SubjectSelectList = SubjectSelectList;
                    return View(lesson);
                }
            }
            return RedirectToAction(nameof(Index));
        }
        [HttpPost]
        public ActionResult Edit(int? id, Lesson lesson)
        {
            ModelState.Remove("Subject");
            if (ModelState.IsValid)
            {
                if (id != lesson.LessonId)
                {
                    return NotFound();
                }
                try
                {
                    _repo.Update(lesson);
                    _repo.Save();
                    return RedirectToAction(nameof(Index));
                }
                catch
                {
                    var subjects = _context.Subjects.ToList();
                    var SubjectSelectList = new SelectList(subjects, "SubjectId", "SubjectName");
                    ViewBag.SubjectSelectList = SubjectSelectList;
                    return View(lesson);
                }
            }
            else
            {
                var subjects = _context.Subjects.ToList();
                var SubjectSelectList = new SelectList(subjects, "SubjectId", "SubjectName");
                ViewBag.SubjectSelectList = SubjectSelectList;
                return View(lesson);
            }
          
        }
       
        public IActionResult Search(string searchString, int? page)
        {
            // Lấy danh sách các role từ database, có thể thay thế bằng logic của bạn
            var lessons = _context.Lessons.Include(s => s.Subject).ToList();
            var subjects = _context.Subjects.ToList();
            ViewBag.Subjects = subjects;
            ViewBag.SearchString = searchString ?? String.Empty;
            if (!string.IsNullOrEmpty(searchString))
            {
                lessons = lessons.Where(l => l.Topic.IndexOf(searchString, StringComparison.OrdinalIgnoreCase) >= 0).ToList();
            }
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View("Index", lessons.ToPagedList(pageNumber, pageSize));
        }
        public IActionResult SortBySlot(string sortOrder, int? page)
        {
            ViewData["SortOrder"] = sortOrder;

            var lessons = _context.Lessons.Include(s => s.Subject).ToList();

            switch (sortOrder)
            {
                case "asc":
                    lessons = lessons.OrderBy(l => l.Order).ToList();
                    var subjects = _context.Subjects.ToList();
                    ViewBag.Subjects = subjects;
                    break;
                case "desc":
                    lessons = lessons.OrderByDescending(l => l.Order).ToList();
                    subjects = _context.Subjects.ToList();
                    ViewBag.Subjects = subjects;
                    break;
                default:
                    // Mặc định sắp xếp theo thứ tự tăng dần
                    lessons = lessons.OrderBy(l => l.Order).ToList();
                    subjects = _context.Subjects.ToList();
                    ViewBag.Subjects = subjects;
                    break;
            }
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View("Index", lessons.ToPagedList(pageNumber, pageSize));
        }
        public IActionResult FilterBySubject(int? subjectId, int? page)
        {
            var lesssons = _context.Lessons.Include(s => s.Subject).ToList();
            var subjects = _context.Subjects.ToList();
            ViewBag.Subjects = subjects;
            if (subjectId.HasValue)
            {
                lesssons = lesssons.Where(l => l.SubjectId == subjectId.Value).ToList();
            }
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View("Index", lesssons.ToPagedList(pageNumber, pageSize));
        }
    }
}

KRS_G54/KRS_G54/Areas/Manager/Views/Lesson/Create.cshtml
@model KRS_G54.Models.Lesson
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, AuthoringTagHelpers
@{
    ViewData["Title"] = "Create";
    Layout = "/Areas/Manager/Views/Shared/_Layout.cshtml";
}
<script src="~/ckeditor/ckeditor.js"></script>
<h1>Create Lesson</h1>
<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row">
                <div class="form-group col-lg-6">
                    <label>Topic<span class="text-danger">*</span></label>
                    <input asp-for="Topic" class="form-control" />
                    <span asp-validation-for="Topic" class="text-danger"></span>
                </div>
                <div class="form-group col-lg-6">
                    <label>Slot<span class="text-danger">*</span></label>
                    <input asp-for="Order" class="form-control" />
                    <span asp-validation-for="Order" class="text-danger"></span>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-lg-6">
                    <label>Subject</label>
                    <select asp-for="SubjectId" class="form-control" asp-items="@ViewBag.SubjectSelectList">
                    </select>
                </div>
            </div>
           
            <div>
                @Html.ActionLink("Back to List", "Index",new {}, new {@class = "btn btn-outline-primary text-black mr-2"})
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

KRS_G54/KRS_G54/Areas/Manager/Views/Lesson/Edit.cshtml
@model KRS_G54.Models.Lesson
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, AuthoringTagHelpers
@{
    ViewData["Title"] = "Edit";
    Layout = "/Areas/Manager/Views/Shared/_Layout.cshtml";
}
<script src="~/ckeditor/ckeditor.js"></script>
<h1 style="text-align:center">Edit Lesson</h1>

<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group col-lg-6" style="display:none">
                <label asp-for="LessonId" class="control-label"></label>
                <input asp-for="LessonId" class="form-control" readonly />
                <span asp-validation-for="LessonId" class="text-danger"></span>
            </div>
            <div class="row">
                <div class="form-group col-lg-6">
                    <label asp-for="Topic" class="control-label"></label>
                    <input asp-for="Topic" class="form-control" required />
                    <span asp-validation-for="Topic" class="text-danger"></span>
                </div>
                <div class="form-group col-lg-6">
                    <label>Slot</label>
                    <input asp-for="Order" class="form-control" required />
                    <span asp-validation-for="Order" class="text-danger"></span>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-lg-6">
                    <label class="control-label">Subject</label>
                    <select asp-for="SubjectId" class="form-control" asp-items="@ViewBag.SubjectSelectList">
                    </select>

                    <span asp-validation-for="SubjectId" class="text-danger"></span>
                </div>

            </div>
           
            

            <div class="form-group">
                @Html.ActionLink("Back to List", "Index",new {}, new {@class = "btn btn-outline-primary text-black mr-2"})
                <input type="submit" value="Update" class="btn btn-success" />
            </div>


        </form>
    </div>
</div>

KRS_G54/KRS_G54/Areas/Manager/Views/Lesson/Index.cshtml
@using KRS_G54.Models;
@using X.PagedList;
@model IPagedList<KRS_G54.Models.Lesson>
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, AuthoringTagHelpers
@{
    ViewData["Title"] = "Manager Page";
    Layout = "/Areas/Manager/Views/Shared/_Layout.cshtml";
}
<style>
    ::-webkit-scrollbar {
        width: 12px;
    }

    ::-webkit-scrollbar-track {
        background: #f1f1f1;
    }

    ::-webkit-scrollbar-thumb {
        background: #888;
        border-radius: 10px;
    }

        ::-webkit-scrollbar-thumb:hover {
            background: #555;
        }

    .select-with-scroll {
        overflow-y: auto;
        max-height: 200px;
    }
</style>
<h1>Lesson Management</h1>
<div class="container" style="margin:0px">
    <div class="row" style=" display: inline-flex;justify-content: space-around;">
        <div class="col">
            <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Fillter by Subject...
                </button>
                <div class="dropdown-menu select-with-scroll" aria-labelledby="dropdownSortButton">
                    <a class="dropdown-item" href="@Url.Action("FilterBySubject", "Lesson", new { subjectId = (int?)null })">All</a>

                    @foreach (Subject item in ViewBag.Subjects)
                    {
                        <a class="dropdown-item" href="@Url.Action("FilterBySubject", "Lesson", new { subjectId = item.SubjectId })">@item.SubjectCode</a>
                    }
                </div>
            </div>
        </div>
        <div class="col">

            <form asp-controller="Lesson" asp-action="Search">
                <div class="input-group">
                    <input type="text" name="searchString" class="form-control" placeholder="Search..." value="@ViewBag.SearchString">
                    <div class="input-group-append">
                        <button type="submit" class="btn btn-primary">Search</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<table class="table" style="margin-top:30px">
    <thead>
        <tr>
           
            <th>Topic</th>
            <th>Slot<a title="Sort ascending" href="@Url.Action("SortBySlot", new { sortOrder = "asc" })"><span class="arrow-up"></span></a><a title="Sort descending" href="@Url.Action("SortBySlot", new { sortOrder = "desc" })"><span class="arrow-down"></span></a></th>
            <th>Subject</th>
            <th>Action</th>

        </tr>
    </thead>
    <tbody>
        @foreach (var lesson in Model)
        {
            <tr>
                <td>@lesson.Topic</td>
                <td>@lesson.Order</td>
                <td>@lesson.Subject.SubjectCode</td>
                <td>
                    <form method="post" asp-action="UpdateStatus">
                        
                        <div class="d-flex align-items-center">
                            
                           
                            @Html.ActionLink("Edit", "Edit", new {Id = lesson.LessonId}, new {@class = "btn btn-success"})
                        </div>
                    </form>
                </td>

            </tr>
        }
    </tbody>
</table>
<div class="text-center">
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            <li class="page-item @(Model.HasPreviousPage ? "" : "disabled")">
                <a class="page-link" href="@Url.Action("Index", new { page = Model.PageNumber - 1 })" tabindex="-1" style="background-color: transparent;border: none;">⬅️</a>
            </li>
            @for (var i = 1; i <= Model.PageCount; i++)
            {
                <li class="page-item @(i == Model.PageNumber ? "active" : "")">
                    <a class="page-link" href="@Url.Action("Index", new { page = i })">@i</a>
                </li>
            }
            <li class="page-item @(Model.HasNextPage ? "" : "disabled")">
                <a class="page-link" href="@Url.Action("Index", new { page = Model.PageNumber + 1 })" style="background-color: transparent;border: none;">➡️</a>
            </li>
        </ul>
    </nav>
</div>