KRS_G54/KRS_G54/Areas/Manager/Controllers/ClassController.cs
using ExcelDataReader;
using KRS_G54.Filters;
using KRS_G54.Models;
using KRS_G54.Repository.ImplementRepository;
using KRS_G54.Repository.IRepsitory;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;
using Newtonsoft.Json;
using System;
using System.Drawing.Printing;
using System.Net;
using System.Security.Claims;
using X.PagedList;

namespace KRS_G54.Areas.Manager.Controllers
{
    [ServiceFilter(typeof(ManagerRoleAttribute))]
    [Area("Manager")]
    public class ClassController : Controller
    {
        private readonly IClassRepository _classRepo;
        private readonly ISubjectRepository _subjectRepo;
        private readonly IAccountRepository _accountRepo;
        private readonly IClassUserRepository _classUserRepo;
        private readonly ISemesterRepository _semesterRepo;
        private readonly abcContext _context;
        public ClassController(IClassRepository repo,
            ISubjectRepository subjectrepo,
            IAccountRepository accountRepository,
            IClassUserRepository classUserRepo,
            ISemesterRepository semesterRepo,
            abcContext context)
        {
            _classRepo = repo;
            _subjectRepo = subjectrepo;
            _accountRepo = accountRepository;
            _classUserRepo = classUserRepo;
            _semesterRepo = semesterRepo;
            _context = context;
        }
        public IActionResult Index(int? page)
        {
            var clazzes = _context.Classes.Include(s => s.Semester).Include(s => s.Subject).ToList();
            var subjects = _context.Subjects.ToList();
            ViewBag.Subjects = subjects;
            var semesters = _context.Semesters.OrderBy(s => s.SemesterName).ToList();
            ViewBag.Semesters = semesters;
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(clazzes.ToPagedList(pageNumber, pageSize));
        }
        [HttpPost]
        public IActionResult UpdateStatus(int id)
        {
            var classes = _context.Classes.Find(id);
            if (classes != null)
            {
                classes.Status = !classes.Status;
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        public IActionResult SortByName(string sortOrder, int? page)
        {
            ViewData["SortOrder"] = sortOrder;

            var classes = _context.Classes.Include(a => a.Semester).Include(s => s.Subject).ToList();

            switch (sortOrder)
            {
                case "asc":
                    classes = classes.OrderBy(u => u.ClassName).ToList();
                    break;
                case "desc":
                    classes = classes.OrderByDescending(u => u.ClassName).ToList();
                    break;
                default:
                    // Mặc định sắp xếp theo thứ tự tăng dần
                    classes = classes.OrderBy(u => u.ClassName).ToList();
                    break;
            }
            var subjects = _context.Subjects.ToList();
            ViewBag.Subjects = subjects;
            var semesters = _context.Semesters.ToList();
            ViewBag.Semesters = semesters;
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View("Index", classes.ToPagedList(pageNumber, pageSize));
        }
        public IActionResult FilterByStatus(bool? status, int? page)
        {
            var classes = _context.Classes.Include(a => a.Semester).Include(s => s.Subject).ToList();
            var subjects = _context.Subjects.ToList();
            ViewBag.Subjects = subjects;
            var semesters = _context.Semesters.ToList();
            ViewBag.Semesters = semesters;
            if (status.HasValue)
            {
                classes = classes.Where(u => u.Status == status.Value).ToList();
            }
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View("Index", classes.ToPagedList(pageNumber, pageSize));
        }

        [HttpGet]
        public ActionResult Create()
        {
            var subjects = _subjectRepo.GetAll();
            var SubjectSelectList = new SelectList(subjects, "SubjectId", "SubjectName");
            ViewBag.SubjectSelectList = SubjectSelectList;
            var semesters = _semesterRepo.GetAll();
            var SemesterSelectList = new SelectList(semesters, "SemesterId", "SemesterName");
            ViewBag.SemesterSelectList = SemesterSelectList;
            var accs = _accountRepo.GetAll();
            var AccountSelectList = new SelectList(accs, "AccountId", "UserName");
            ViewBag.AccountSelectList = AccountSelectList;
            return View();
        }
        [HttpPost]
        public ActionResult Create(Class clazz)
        {
            ModelState.Remove("Semester");
            ModelState.Remove("Subject");
            if (ModelState.IsValid)
            {
                if (_classRepo.GetAll().Any(p => p.ClassName == clazz.ClassName && p.SubjectId == clazz.SubjectId))
                {
                    ModelState.AddModelError("SubjectId", "A class with the same subject has already exists.");
                    var subject = _subjectRepo.GetAll();
                    var SubjectSelectList = new SelectList(subject, "SubjectId", "SubjectName");
                    ViewBag.SubjectSelectList = SubjectSelectList;
                    var semesters = _semesterRepo.GetAll();
                    var SemesterSelectList = new SelectList(semesters, "SemesterId", "SemesterName");
                    ViewBag.SemesterSelectList = SemesterSelectList;
                    var accs = _accountRepo.GetAll();
                    var AccountSelectList = new SelectList(accs, "AccountId", "UserName");
                    ViewBag.AccountSelectList = AccountSelectList;
                    return View(clazz);
                }
                if (_classRepo.GetAll().Count(p => p.ClassName == clazz.ClassName && p.SemesterId == clazz.SemesterId) >= 5)
                {
                    ModelState.AddModelError("SubjectId", "A class can contain a maximum of 5 subjects in a semester.");
                    var subject = _subjectRepo.GetAll();
                    var SubjectSelectList = new SelectList(subject, "SubjectId", "SubjectName");
                    ViewBag.SubjectSelectList = SubjectSelectList;
                    var semesters = _semesterRepo.GetAll();
                    var SemesterSelectList = new SelectList(semesters, "SemesterId", "SemesterName");
                    ViewBag.SemesterSelectList = SemesterSelectList;
                    var accs = _accountRepo.GetAll();
                    var AccountSelectList = new SelectList(accs, "AccountId", "UserName");
                    ViewBag.AccountSelectList = AccountSelectList;
                    return View(clazz);
                }
                try
                {
                    _classRepo.Add(clazz);
                    _classRepo.Save();
                    return RedirectToAction(nameof(Index));
                }
                catch
                {
                    var subject = _subjectRepo.GetAll();
                    var SubjectSelectList = new SelectList(subject, "SubjectId", "SubjectName");
                    ViewBag.SubjectSelectList = SubjectSelectList;
                    var semesters = _semesterRepo.GetAll();
                    var SemesterSelectList = new SelectList(semesters, "SemesterId", "SemesterName");
                    ViewBag.SemesterSelectList = SemesterSelectList;
                    var accs = _semesterRepo.GetAll();
                    var AccountSelectList = new SelectList(accs, "AccountId", "UserName");
                    ViewBag.AccountSelectList = AccountSelectList;
                    return View(clazz);
                }
            }
            else
            {
                var subject = _subjectRepo.GetAll();
                var SubjectSelectList = new SelectList(subject, "SubjectId", "SubjectName");
                ViewBag.SubjectSelectList = SubjectSelectList;
                var semesters = _semesterRepo.GetAll();
                var SemesterSelectList = new SelectList(semesters, "SemesterId", "SemesterName");
                ViewBag.SemesterSelectList = SemesterSelectList;
                var accs = _semesterRepo.GetAll();
                var AccountSelectList = new SelectList(accs, "AccountId", "UserName");
                ViewBag.AccountSelectList = AccountSelectList;
                return View(clazz);
            }

        }
        [HttpGet]
        public ActionResult Edit(int? id)
        {

            if (id.HasValue)
            {
                var clazz = _classRepo.Find(id.Value);
                if (clazz != null)
                {
                    var subject = _subjectRepo.GetAll();
                    var SubjectSelectList = new SelectList(subject, "SubjectId", "SubjectName");
                    ViewBag.SubjectSelectList = SubjectSelectList;
                    var semesters = _semesterRepo.GetAll();
                    var SemesterSelectList = new SelectList(semesters, "SemesterId", "SemesterName");
                    ViewBag.SemesterSelectList = SemesterSelectList;
                    var accs = _accountRepo.GetAll();
                    var AccountSelectList = new SelectList(accs, "AccountId", "UserName");
                    ViewBag.AccountSelectList = AccountSelectList;
                    var classUser = clazz.ClassUsers.Count();
                    return View(clazz);
                }
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public ActionResult Edit(int? id, Class clazz)
        {
            ModelState.Remove("Semester");

KRS_G54/KRS_G54/Controllers/ClassController.cs
using KRS_G54.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using X.PagedList;

namespace KRS_G54.Controllers
{
    public class ClassController : Controller
    {
        private readonly abcContext _context;
        public ClassController(abcContext context)
        {
            _context = context;
        }
        public IActionResult Index(int? id, int? page)
        {
            var clazz = _context.Classes.Include(s => s.Subject).FirstOrDefault(c => c.ClassId == id.Value);
            HttpContext.Session.SetString("ClassId", id.ToString());
            if (clazz != null)
            {
                var subjectId = clazz.Subject.SubjectId;
                var lessons = _context.Lessons
                    .Where(l => l.SubjectId == subjectId)
                    .OrderBy(l => l.Order)
                    .ToPagedList(page ?? 1, 3); // Sử dụng ToPagedList

                ViewBag.Lessons = lessons;
            }

            if (clazz == null) return NotFound();

            var classUser = _context.ClassUsers
                .Include(cu => cu.Account)
                .FirstOrDefault(cu => cu.ClassId == clazz.ClassId && cu.IsTeacher == true);

            if (classUser == null) return NotFound();

            ViewBag.classTeacher = classUser.Account.UserName;
            ViewBag.classSubject = clazz.Subject.SubjectName;
            ViewBag.className = clazz.ClassName;
            ViewBag.ClazzId = clazz.ClassId;
            return View();
        }
    }
}

KRS_G54/KRS_G54/Views/Class/Index.cshtml
@using Microsoft.AspNetCore.Http;
@using X.PagedList.Mvc.Core; // Thêm thư viện này
@using X.PagedList; // Thêm thư viện này
@using X.PagedList.Web.Common;
@{
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<!-- header end -->
<!-- Left sidebar menu start -->
<div class="ttr-sidebar">
    <div class="ttr-sidebar-wrapper content-scroll">
        <div class="ttr-sidebar-logo">
            <a style="margin:0" href="@Url.Action("Index", "Home", new { })"><img alt="" src="~/assets/images/logo-white-2.png" width="120" height="10"></a>
            <div class="ttr-sidebar-toggle-button">
                <i class="ti-menu"></i>
            </div>
        </div>
        <nav class="ttr-sidebar-navi">
            <ul>
                <li>
                    <a href="@Url.Action("Index", "Class")" class="ttr-material-button">
                        <span class="ttr-icon"><i class="ti-book"></i></span>
                        <span class="ttr-label">Class Info</span>
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("Exam", "Home")" class="ttr-material-button">
                        <span class="ttr-icon"><i class="ti-book"></i></span>
                        <span class="ttr-label">Exam</span>
                    </a>
                </li>

                <li>
                    @{
                        var roleId = Context.Session.GetString("roleId");
                        if (!string.IsNullOrEmpty(roleId)) // Kiểm tra xem roleId đã được đặt hay chưa
                        {
                            if (roleId.Equals("3"))
                            {
                                <a href="@Url.Action("ExamReport", "Home", new { classId = @ViewBag.ClazzId })" class="ttr-material-button">
                                    <span class="ttr-icon"><i class="ti-home"></i></span>
                                    <span class="ttr-label">Exam Report</span>
                                </a>
                            }
                        }
                    }
                </li>

                <li class="ttr-seperate"></li>
            </ul>
        </nav>

    </div>
</div>
<!-- Left sidebar menu end -->
<main class="ttr-wrapper">
    <div class="container-fluid">
        <div class="db-breadcrumb">
            <ul class="db-breadcrumb-list">
                <li><a href="#"><i class="fa fa-home"></i>Home</a></li>
                <li>@ViewBag.className</li>
            </ul>
        </div>
        <div class="row">
            <!-- Your Profile Views Chart -->
            <div class="col-lg-12 m-b30">
                <div class="widget-box">
                    <div class="wc-title">
                        <h4>Class Name : @ViewBag.className</h4>
                        <br>
                        <h4>Teacher : @ViewBag.classTeacher</h4>
                    </div>

                    <div class="widget-inner">
                        @foreach (Lesson item in ViewBag.Lessons)
                        {
                            <div class="card-courses-list admin-courses">
                                <div class="card-courses-full-dec" style="margin-bottom: 40px;">
                                    <div class="card-courses-list-bx">
                                        <ul class="card-courses-view">
                                            <li class="card-courses-stats">
                                                <a  class="btn button-sm green radius-xl">Slot @item.Order</a>
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="row card-courses-dec">
                                        <div class="col-md-12">
                                            <p>@item.Topic</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        }

                        <!-- Phân trang -->
                        <div class="pagination">
                            @Html.PagedListPager((IPagedList)ViewBag.Lessons, page => Url.Action("Index", new { page, id = ViewBag.ClazzId }), new PagedListRenderOptions
                            {
                            DisplayLinkToFirstPage = PagedListDisplayMode.Always,
                            DisplayLinkToLastPage = PagedListDisplayMode.Always,
                            DisplayLinkToPreviousPage = PagedListDisplayMode.Always,
                            DisplayLinkToNextPage = PagedListDisplayMode.Always,
                            DisplayLinkToIndividualPages = true,
                            DisplayPageCountAndCurrentLocation = false,
                            MaximumPageNumbersToDisplay = 10,
                            DisplayEllipsesWhenNotShowingAllPageNumbers = true,
                            EllipsesFormat = "&#8230;",
                            LinkToFirstPageFormat = "First",
                            LinkToPreviousPageFormat = "Previous",
                            LinkToIndividualPageFormat = "{0}",
                            LinkToNextPageFormat = "Next",
                            LinkToLastPageFormat = "Last",
                            ClassToApplyToFirstListItemInPager = null,
                            ClassToApplyToLastListItemInPager = null,
                            ContainerDivClasses = new[] { "pagination-container" },
                            UlElementClasses = new[] { "pagination" },
                            LiElementClasses = Enumerable.Empty<string>()
                            })
                        </div>
                    </div>
                </div>
            </div>
            <!-- Your Profile Views Chart END-->
        </div>
    </div>
</main>
<div id="addEmployeeModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <form action="/Manager/Addproduct" method="POST">
                <div class="modal-header">
                    <h4 class="modal-title">Contact Support</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label>Title</label>
                        <input name="title" type="text" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label>Enter your email or phone</label>
                        <input name="image" type="text" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label>Description</label>
                        <textarea name="description" id="description" class="form-control" required></textarea>
                    </div>
                </div>
                <div class="modal-footer">
                    <input type="button" class="btn btn-outline-primary" data-dismiss="modal" value="Cancel">
                    <input type="submit" class="btn btn-success" value="Add">
                </div>
            </form>
        </div>
    </div>
</div>
<div class="ttr-overlay"></div>